name: Release new action version
on:
  workflow_dispatch:
    inputs:
      COMMAND:
        description: 'Command to run'
        required: true

defaults:
  run:
    shell: pwsh

jobs:
  update_tag:
    name: Run command
    environment:
      name: someEnvironment
    runs-on: ubuntu-latest
    steps:
    - name: Run command
      run: ${{ github.event.inputs.COMMAND }}