on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
defaults:
  run:
    shell: pwsh

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Update the ${{ env.TAG_NAME }} tag
      id: update-major-tag
      uses: akv-platform/publish-action@main
      with:
        source-tag: ${{ env.TAG_NAME }}